#!/bin/bash

set -e
set -o pipefail

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

printf "\n Begin prep ....\n\n"

if [[ $CHECK == "check" ]]; then
  printf "\n    will execute ...  apt-get install -y git curl libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libncurses5-dev libffi-dev libgdbm-dev"
  printf "\n    will execute ...  apt-get install -y libvips-dev --no-install-recommends"
else
  apt-get install -y git curl libssl-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libncurses5-dev libffi-dev libgdbm-dev
  apt-get install -y libvips-dev --no-install-recommends
fi

printf "\n\n  completed  prep\n\n"
