#!/bin/bash

set -e
set -o pipefail

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

printf "\n Begin ruby install ....\n\n"

if [[ $CHECK == "check" ]]; then
  printf "\n    will execute ...  apt-get install -y ruby-full ruby-dev ruby-bundler"
else
  apt-get install -y ruby-full ruby-dev ruby-bundler
fi

printf "\n\n  completed ruby install\n\n"