#!/bin/bash

set -e
set -o pipefail

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

printf "\n Begin ruby ....\n\n"

if [[ $CHECK == "check" ]]; then
  echo "************ not yet implemented  ******************"
else
  echo "************ not yet implemented  ******************"
fi

printf "\n\n  completed  ruby\n\n"